apiVersion: v1
kind: Service
metadata:
  name: p2p-bootnode
  labels:
    app: p2p-node
    role: bootnode
spec:
  type: NodePort
  ports:
  - port: 30001
    name: gossip
    protocol: TCP
  selector:
    app: p2p-node
    role: bootnode
