apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p-bootnode
  labels:
    app: p2p-node
    role: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2p-node
      role: bootnode
  template:
    metadata:
      labels:
        app: p2p-node
        role: bootnode
    spec:
      containers:
        - name: bootnode
          image: zjshen/go-p2p:latest
          imagePullPolicy: Always
          command: ["/go/src/github.com/zjshen14/go-p2p/bin/main"]
          args: ["-secureio=true", "-broadcast=false", "-gossip=true", "-exthost=p2p-bootnode"]
          ports:
          - containerPort: 30001
            protocol: TCP
          - name: metrics
            containerPort: 8080
            protocol: TCP
          env:
            - name: P2P_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
