apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: p2p-node-metrics
  labels:
    app: p2p-node
    prometheus: kube-prometheus
    namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: node-metrics
      app: p2p-node
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  name: p2p-metrics
  labels:
    app: p2p-node
    component: node-metrics
spec:
  ports:
  - port: 8080
    name: metrics
    protocol: TCP
  selector:
    app: p2p-node
