apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p-bootnode
  labels:
    app: p2p-node
spec:
  serviceName: "p2p-node"
  replicas: 100
  selector:
    matchLabels:
      app: p2p-node
  template:
    metadata:
      labels:
        app: p2p-node
    spec:
      containers:
        - name: p2pnode
          image: zjshen14/go-p2p:latest
          imagePullPolicy: Always
          command: ["/go/src/github.com/zjshen14/go-p2p/bin/main"]
          args: ["-seed=0", "-bootstrapaddr=p2p-bootnode:30001"]
          ports:
          - containerPort: 30001
            protocol: TCP
          - name: metrics
            containerPort: 8080
            protocol: TCP
          env:
            - name: P2P_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
